language: go
go:
- 1.5.1


# Grab newest version and suck down
install:
    - export FILE=$(curl https://storage.googleapis.com/appengine-sdks/ | grep -oP '(?<=featured/)go_appengine_sdk_linux_amd64-[^\<]*' | head -1)
    - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
    - unzip -q $FILE

# Run build and tests
script:
    #- ./go_appengine/goapp test ./tests; # If you are testing
    - ./go_appengine/goapp build ./server; # Wherever you keep your stuff
